name: Trigger EventBridge Rule from Webhook
on:
  push:
    branches:
      - main

jobs:
  trigger-eventbridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Invoke EventBridge Rule
        run: |
          aws events put-events --entries '[{"Source":"custom.github","DetailType":"webhook.event","Detail":"{\"message\": \"Webhook event received from GitHub\"}"}]' --event-bus-name webhook-event-bridge
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: YOUR_AWS_REGION
